#!/bin/bash
help="Chat interactively with an AI model

Usage: aichat [OPTIONS]

OPTIONS:
    -h, --help      Print help and exit

    See \`aicomplete --help\`

ENVIRONMENT VARIABLES:
    AI_DEVELOPER    An optional file containing a developer prompt
    
    See \`aicomplete --help\`
"
if [[ "$@" =~ "--help"|"-h" ]]; then
    echo "$help"
    exit 0
fi

if [ ! -z "$AI_DEVELOPER" ]; then
    history=$(aimessage --role developer "$AI_DEVELOPER")
else
    history=$(aimessage --empty)
fi
while true; do
    printf "user> "
    prompt=$(cat -)
    echo
    if [ -z "$prompt" ]; then
        break
    fi
    history=$(aicat-messages <(echo "$history") <(echo "$prompt" | aimessage))
    
    printf "assistant> "
    response=$(echo "$history" | aicomplete --stream $@ | tee /dev/tty)
    echo

    history=$(aicat-messages <(echo "$history") <(echo "$response" | aimessage --role assistant))
done