#!/bin/bash
file=$1
shift

if [ ! -z "$AI_DEVELOPER" ]; then
    history=$(aimessage --role developer "$AI_DEVELOPER")
else
    history=$(aimessage --empty)
fi
while true; do
    printf "user> "
    prompt=$(cat -)
    echo
    if [ -z "$prompt" ]; then
        break
    fi
    prompt=$(echo "$prompt" | cat - <(aifile "$file"))
    history=$(aicat-messages <(echo "$history") <(echo "$prompt" | aimessage))
    
    printf "assistant> "
    response_file=$(mktemp)
    echo "$history" |
     aicomplete --stream --prediction "$file" | 
     tee "$response_file" |
     aiextract-block --block-index 0 --redirect-rest /dev/tty |
     aisponge "$file"
    echo

    history=$(aicat-messages <(echo "$history") <(aimessage --role assistant "$response_file"))
done