#!/bin/bash
help="Interactively edit a file with an AI model and chat

Usage: aiedit <file> [OPTIONS]

OPTIONS:
    -h, --help      Print help and exit

    See \`aicomplete --help\`

ENVIRONMENT VARIABLES:
    AI_DEVELOPER    An optional file containing a developer prompt
    
    See \`aicomplete --help\`
"
if [[ "$@" =~ "--help"|"-h" ]]; then
    echo "$help"
    exit 0
fi

file=$1
shift

if [ ! -z "$AI_DEVELOPER" ]; then
    history=$(aimessage --role developer "$AI_DEVELOPER")
else
    history=$(aimessage --empty)
fi
while true; do
    printf "user> "
    prompt=$(cat -)
    echo
    if [ -z "$prompt" ]; then
        break
    fi
    prompt=$(echo "$prompt" | cat - <(aifile "$file"))
    history=$(aicat-messages <(echo "$history") <(echo "$prompt" | aimessage))
    
    printf "assistant> "
    response_file=$(mktemp)
    echo "$history" |
     aicomplete --stream --prediction "$file" $@ | 
     tee "$response_file" |
     aiextract-block --block-index 0 --redirect-rest /dev/tty |
     aisponge "$file"
    echo

    history=$(aicat-messages <(echo "$history") <(aimessage --role assistant "$response_file"))
done